import{a as c,S as f,i as l}from"./assets/vendor-145b7b72.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="https://api.thecatapi.com/v1/",m="live_8Wl1NUYFJhvYgeZls4YXPXSn1CRGnyvhRR4L69kQeeLTgPieF5v9ebYgSulmpN6r";c.defaults.headers.common["x-api-key"]=m;const g=async()=>{const{data:o}=await c.get(`${d}breeds`);return o},h=async o=>{const{data:s}=await c.get(`${d}images/search?breed_ids=${o}`);if(s.length===0)throw new Error("No cats found for this breed!");return s},r={select:document.querySelector(".js-breed-select"),catInfo:document.querySelector(".js-cat-info"),loader:document.querySelector(".js-loader")};y();r.select.addEventListener("change",L);async function y(){try{r.loader.classList.remove("isHidden");const s=(await g()).map(n=>({text:n.name,value:n.id}));new f({select:"#single",data:s}),r.select.classList.remove("isHidden")}catch(o){console.log("error",o),l.show({message:"Oops! Something went wrong! Try reloading the page!",color:"red",position:"topRight"})}finally{r.loader.classList.add("isHidden")}}async function L(o){const s=o.target.value;try{r.catInfo.classList.add("isHidden"),r.loader.classList.remove("isHidden");const i=(await h(s)).map(e=>{const{name:t,description:a,life_span:p,temperament:u}=e.breeds[0];return`
          <div class="block">
          <img src="${e.url}" alt="${t}" width="300">
          <p><span class="title">Breed:</span> ${t}</p>
          <p><span class="title">Description:</span> ${a}</p>
          <p><span class="title">Life span:</span> ${p}</p>
          <p><span class="title">Temperament:</span> ${u}</p>
          </div>
          `}).join("");r.catInfo.innerHTML=i,r.catInfo.classList.remove("isHidden")}catch(n){console.log("error",n),l.show({message:"Oops! Something went wrong! Try reloading the page!",color:"red",position:"topRight"})}finally{r.loader.classList.add("isHidden")}}
//# sourceMappingURL=commonHelpers.js.map
